### ISSUE TITLE
TypeError: wer() got an unexpected keyword argument 'standardize'

### ISSUE THREAD

**Issue by hechengzhi985** [burchim/EfficientConformer#27]
Traceback (most recent call last):
  File "main.py", line 222, in <module>
    main(0, args)
  File "main.py", line 121, in main
    model.fit(dataset_train, 
  File "EfficientConformer-master/models/model.py", line 344, in fit
    raise e
  File "EfficientConformer-master/models/model.py", line 303, in fit
    wer, truths, preds, val_loss = self.evaluate(dataset, val_steps, verbose_val, eval_loss=True)
  File "EfficientConformer-master/models/model.py", line 425, in evaluate
    batch_wer = jiwer.wer(outputs_true, outputs_pred, standardize=True)
TypeError: wer() got an unexpected keyword argument 'standardize'

**Comment by hechengzhi985** [comment]
jiwer.wer(outputs_true, outputs_pred, standardize=True)

**Comment by Rawsea** [comment]
I met the same issue. Just change jiwer version to 2.2.1.
```shell
pip install jiwer==2.2.1
```

**Comment by burchim** [comment]
Hi, the standardize keyword was removed in newer versions. The repo was not updated yet so the current requirements.txt file do not specify the version to install. This is why you probably downloaded a newer version.
